accounts:
  - name: alice
    coins: ["200000000ujkl", "100000000ujwl"]
  - name: bob
    coins: ["100000000ujkl"]
validator:
  name: alice
  staked: "100000000ujkl"
client:
  openapi:
    path: "docs/static/openapi.yml"
  vuex:
    path: "vue/src/store"
faucet:
  name: bob
  coins: ["1000000ujkl"]
init:
  app:
    minimum-gas-prices: "0.02ujkl"
genesis:
  app_state:
    staking:
      params:
        bond_denom: "ujkl"